- platform: generic
  still_image_url: http://s15731777.onlinehome-server.info/readImage.asp?dummy=1513334922984
  name: Borkum
- platform: generic
  still_image_url: https://livecloud-s3.freetls.fastly.net/cb-11a75d29/media/e3c83f06-50aa-4e19-879a-9af37d2930ac/preview/1280x720.jpg
  name: Borkum Wetter
- platform: generic
  name: Eingang
  username: !secret fritz_user
  password: !secret http_password
  authentication: digest
  framerate: 1
  still_image_url: http://10.10.0.16:80/cgi-bin/snapshot.cgi
- platform: generic
  name: Hinten
  username: !secret fritz_user
  password: !secret http_password
  framerate: 1
  still_image_url: http://10.10.0.17:80/cgi-bin/snapshot.cgi
 
 
- platform: mjpeg
  name: Drucker 3d Camera 
  still_image_url: http://octopi/webcam/?action=snapshot
  mjpeg_url: http://octopi/webcam/?action=stream
