alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

binary_sensor:

  - platform: mqtt
    name: "Kuechentuer Kontakt Batt"
    state_topic: "home/Alarm/Batt/OpenFensterKueche"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "Wohnzimmertuer Kontakt Batt"
    state_topic: "home/Alarm/Batt/OpenTuerWohnzimmer"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "Haustuer Kontakt Batt"
    state_topic: "home/Alarm/Batt/OpenDoorHaus"
    qos: 0
    device_class: battery
    
  - platform: mqtt
    name: "Kellerfenster Kontakt Batt"
    state_topic: "home/Alarm/Batt/OpenFensterKeller"
    qos: 0
    device_class: battery
  - platform: mqtt
    name: "Kellerfenster Kontakt L Batt"
    state_topic: "home/Alarm/Batt/OpenFensterKellerL"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "Kellerfenster Kontakt R Batt"
    state_topic: "home/Alarm/Batt/OpenFensterKellerR"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "Wohnzimmerfenster Kontakt R Batt"
    state_topic: "home/Alarm/Batt/OpenFensterWohnzimmerR"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "Wohnzimmerfenster Kontakt L Batt"
    state_topic: "home/Alarm/Batt/OpenFensterWohnzimmerL"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "Wohnzimmerfenster Kontakt Batt"
    state_topic: "home/Alarm/Batt/OpenFensterWohnzimmer"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "Treppenfenster Kontakt Batt"
    state_topic: "home/Alarm/Batt/OpenFensterTreppe"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "WC Fenster Kontakt Batt"
    state_topic: "home/Alarm/Batt/OpenFensterWc"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "Vorratsfenster Kontakt Batt"
    state_topic: "home/Alarm/Batt/OpenFensterVorrat"
    qos: 0
    device_class: battery


  - platform: mqtt
    name: "Kuechenfenster Kontakt Batt"
    state_topic: "home/Alarm/Batt/OpenDoorKueche"
    qos: 0
    device_class: battery
    

