binary_sensor:
  - platform: template
    sensors:
      bs_sun_up:
        friendly_name: "es ist hell"
        value_template: >-
          {{ states.sun.sun.attributes.elevation|float > 0 }}



sensor:

  - platform: mqtt
    name:  aussen Temperatur
    state_topic: "aussen/Sensor/Temperature"
    unit_of_measurement: "°C"
 
  - platform: mqtt
    name:  aussen Feuchte
    state_topic: "aussen/Sensor/Humidity"
    unit_of_measurement: "%"
 
  - platform: mqtt
    name:  aussen Druck
    state_topic: "aussen/Sensor/Pressure"
    unit_of_measurement: "hPa"
    
  - platform: mqtt
    name: "Luft Nievenheim PM10"
    state_topic: "aussen/Sensor/N/PM10"
    json_attributes_topic: "aussen/Sensor/N/attributesPM10"
    
  - platform: mqtt
    name: "Luft Nievenheim PM2.5"
    state_topic: "aussen/Sensor/N/PM25"   
    json_attributes_topic: "aussen/Sensor/N/attributesPM25"
    
  - platform: mqtt
    name: "Luft Straberg PM10"
    state_topic: "aussen/Sensor/PM10"
    json_attributes_topic: "aussen/Sensor/attributes"
    
  - platform: mqtt
    name: "Luft Straberg PM2.5"
    state_topic: "aussen/Sensor/PM25"   
    json_attributes_topic: "aussen/Sensor/attributes"    
