homeassistant:
  customize:

    sensor.hass_uptime:
      friendly_name: Home Assistant Uptime
      icon: mdi:home-assistant
    sensor.ha_github_version:
      friendly_name: "GitHub Version"
      icon: mdi:github-box

sensor:
  ###### VERSIONS

  - platform: version
    name: Installed Version

  - platform: uptime
    name: "HASS Uptime"
    unit_of_measurement: hours



script:
      
  notify_mqtt:
    sequence:
      - service: mqtt.publish
        data_template:
          payload: "{{ message }}"
          topic: homeassistant/tele/notify/message
          qos: 2

  