homeassistant:
  customize:
    sensor.wolfgangda2_cpu_usage:
      friendly_name: DA 2 CPU Auslastung
    media_player.snapcast_client_b827eb3b832a_2:
      friendly_name: Radio Keller

switch:
  - platform: wake_on_lan
    name: Nas3 Wake
    mac_address: "00:11:32:83:E3:3E"
    host: "10.10.0.4"

  - platform: wake_on_lan
    name: Nas2 Wake
    mac_address: "00:08:9B:D1:73:18"
    host: "10.10.0.3"



binary_sensor:


  - platform: mqtt
    name: "Kellerfenster Kontakt L"
    state_topic: 'nodered/alarmkontakte/FensterKellerL'
    device_class: window

  - platform: mqtt
    name: "Kellerfenster Kontakt R"
    state_topic: 'nodered/alarmkontakte/FensterKellerR'
    device_class: window

  - platform: mqtt
    name: "Kellerfenster Kontakt"
    state_topic: 'nodered/alarmkontakte/FensterKellerV'
    device_class: window

sensor:

#qnap

  - platform: qnap
    host: 10.10.0.3
    username: !secret fritz_user
    password: !secret normal_password
    timeout: 30
    monitored_conditions:
      - status
      - cpu_usage
      - memory_percent_used
      - network_tx
      - network_rx
      - volume_percentage_used
      - drive_smart_status

  - platform: synologydsm
    host: 10.10.0.4
    port: 5000
    ssl: false
    username: status
    password: !secret normal_password
    monitored_conditions:
      - network_up
      - network_down
      - cpu_total_load
      - memory_real_usage
      - disk_status
      - disk_smart_status
      - disk_temp
      - volume_percentage_used
      - volume_disk_temp_avg
      - volume_disk_temp_max

  - platform: mqtt
    name: "Waschküche Temperatur"
    state_topic: lled2/Sensor/Temperature
    unit_of_measurement: '°C'
    device_class: temperature
    
  - platform: mqtt
    name: "Waschküche Feuchte"
    state_topic: lled2/Sensor/Humidity
    unit_of_measurement: '%'
    device_class: humidity

  - platform: mqtt
    name: "Waschküche Druck"
    state_topic: lled2/Sensor/Pressure
    unit_of_measurement: 'hPa'
    device_class: pressure

  - platform: mqtt
    name: "Gast Temperatur"
    state_topic: rschalter1/Sensor/Temperature
    unit_of_measurement: '°C'
    device_class: temperature
    
  - platform: mqtt
    name: "Gast Feuchte"
    state_topic: rschalter1/Sensor/Humidity
    unit_of_measurement: '%'
    device_class: humidity

 
        
input_number:

  in_lkellerflur:
    name: Licht Keller Flur Zeit
    mode: slider
    min: 15
    max: 240
    step: 1


  in_temp_kflur:
    name: Keller Flurtemperatur
    mode: slider
    min: 18
    max: 24
    step: 0.5
