switch:
  - platform: mqtt
    name: EinsLive
    state_topic: "nodered/mpd/stat/1live"
    command_topic: "nodered/mpd/cmnd/1live"

    qos: 1
    optimistic: false
    retain: true

  - platform: mqtt
    name: RSH
    state_topic: "nodered/mpd/stat/rsh"
    command_topic: "nodered/mpd/cmnd/rsh"

    qos: 1
    optimistic: false
    retain: true

sensor:
  - platform: mqtt
    name: MPD Title
    state_topic: "nodered/mpd/tele/Title"

  - platform: mqtt
    name: MPD Sender
    state_topic: "nodered/mpd/tele/Sender"

media_player:

  - platform: kodi
    name: amazon_kodi
    host: amazon-cdea109b9.steiner.net

  - platform: mpd
    name: MPD Player
    host: pi-dm

  - platform: snapcast
    host: pi-dm

binary_sensor:
  - platform: template
    sensors:
      bs_play_rsh:
        friendly_name: "RSH läuft"
        device_class: sound
        value_template: >-
                    {% if is_state('media_player.mpd_player', 'playing') %}
                     {% if states.media_player.mpd_player.attributes.media_title[0:4] == 'R.SH' %}
                       true
                     {% else %}
                       false
                     {% endif %}
                    {% else %}
                     false
                    {% endif %}
 

  - platform: template
    sensors:
      bs_play_mpd:
        friendly_name: "MPD läuft"
        device_class: sound
        value_template: "{{ is_state('media_player.mpd_player', 'playing') }}"
