

input_number:
  in_temp_buero:
    name: Büro Soll Temperatur 
    mode: slider
    min: 18
    max: 24
    step: 0.5
    unit_of_measurement: °C
    

binary_sensor:

  - platform: mqtt
    name: "Bürofenster Kontakt"
    state_topic: 'nodered/alarmkontakte/fensterbuero'
    device_class: window

  - platform: mqtt
    name: "Bürofenster Kontakt Batt"
    state_topic: 'nodered/batt/fensterbuero'
    device_class: battery



sensor:    
  - platform: mqtt
    name: "Büro Info"
    state_topic: tsensorbuero/wifi/rssi
    icon: "mdi:information-outline"
    json_attributes_topic: tsensorbuero/wifi/jstatus
    unit_of_measurement: "db"

  - platform: mqtt
    name: "Büro Sensor"
    state_topic: tsensorbuero/SENSOR/absolute_feuchte
    icon: "mdi:information-outline"
    json_attributes_topic: tsensorbuero/SENSOR/sensor
    unit_of_measurement: "g/m³"

  - platform: mqtt
    name: "Büro Temperatur"
    state_topic: tsensorbuero/Sensor/Temperature
    unit_of_measurement: '°C'
    device_class: temperature
    
  - platform: mqtt
    name: "Büro Feuchte"
    state_topic: tsensorbuero/Sensor/Humidity
    unit_of_measurement: '%'
    device_class: humidity
    
  - platform: mqtt
    name: "Büro Druck"
    state_topic: tsensorbuero/Sensor/Pressure
    device_class: pressure
    unit_of_measurement: "hPa"
    
  - platform: template
    sensors:
      buro_soll:
        friendly_name: "Büro Sollwert"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.heizung_buero_heating', 'temperature') }}"
       

