

input_number:
  in_temp_bad:
    name: Bad Soll Temperatur 
    mode: slider
    min: 18
    max: 24
    step: 0.5
    unit_of_measurement: °C
    

binary_sensor:

    
  - platform: mqtt
    name: "Badfenster1 Kontakt"
    state_topic: 'nodered/alarmkontakte/fensterbuero'
    device_class: window

sensor:    
    
  - platform: mqtt
    name: "Bad Info"
    state_topic: tsensorbad/wifi/rssi
    icon: "mdi:information-outline"
    json_attributes_topic: tsensorbad/wifi/jstatus
    unit_of_measurement: "db"

  - platform: mqtt
    name: "Bad Sensor"
    state_topic: tsensorbad/SENSOR/absolute_feuchte
    icon: "mdi:information-outline"
    json_attributes_topic: tsensorbad/SENSOR/sensor
    unit_of_measurement: "g/m³"
    
  - platform: mqtt
    name: "Bad Temperatur"
    state_topic: tsensorbad/Sensor/Temperature
    unit_of_measurement: '°C'
    device_class: temperature
    
  - platform: mqtt
    name: "Bad Feuchte"
    state_topic: tsensorbad/Sensor/Humidity
    unit_of_measurement: '%'
    device_class: humidity
    
  - platform: mqtt
    name: "Bad Druck"
    state_topic: tsensorbad/Sensor/Pressure
    device_class: pressure
    unit_of_measurement: "hPa"