sensor:

  - platform: mqtt
    name: "Speicher Sensor"
    state_topic: speicherbasteln/SENSOR/absolute_feuchte
    icon: "mdi:information-outline"
    json_attributes_topic: speicherbasteln/SENSOR/sensor
    unit_of_measurement: "g/m³"
    
  - platform: mqtt
    name: "Speicher Temperatur"
    state_topic: speicherbasteln/Sensor/Temperature
    unit_of_measurement: '°C'
    device_class: temperature
    
  - platform: mqtt
    name: "Speicher Feuchte"
    state_topic: speicherbasteln/Sensor/Humidity
    unit_of_measurement: '%'
    device_class: humidity
    
  - platform: mqtt
    name: "Speicher Druck"
    state_topic: speicherbasteln/Sensor/Pressure
    device_class: pressure
    unit_of_measurement: "hPa"