homeassistant:
  customize:
    group.all_automations:
      hidden: false
    group.all_scripts:
      hidden: false

      
sensor:

# Bewegung zählen
  - platform: mqtt
    state_topic: "ltreppeoben/tele/COUNT"
    name: Bewegung oben Count
  - platform: mqtt
    state_topic: "lgarage/tele/COUNT"
    name: Bewegung Garage Count    
  - platform: mqtt
    state_topic: "lkellerflur/tele/COUNT"
    name: Bewegung Keller Count    
  - platform: mqtt
    name: Node Red Neue Version
    state_topic: "nodered/tele/nversion"
  - platform: mqtt
    name: Anrufer
    state_topic: "stat/fitzbox/call"    
    
binary_sensor:

  - platform: mqtt
    name: Node Red LWT
    state_topic: nodered/tele/LWT
    payload_on: Online
    payload_off: Offline
    device_class: connectivity 
    
automation:
  alias: Update Available Notification
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: script.notify_mqtt
      data_template:
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
