
input_number:


  in_temp_wohnzimmer:
    name: Wohnzimmertemperatur
    mode: slider
    min: 18
    max: 24
    step: 0.5
    
binary_sensor:
  - platform: mqtt
    name: "Wohnzimmerfenster Kontakt"
    state_topic: 'nodered/alarmkontakte/FensterWohnzimmer'
    device_class: window
    
  - platform: mqtt
    name: "Wohnzimmerfenster Kontakt Batt"
    state_topic: "nodered/batt/FensterWohnzimmer"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "Wohnzimmerfenster Kontakt L"
    state_topic: 'nodered/alarmkontakte/FensterWohnzimmerL'
    device_class: window
    
  - platform: mqtt
    name: "Wohnzimmerfenster Kontakt L Batt"
    state_topic: "nodered/batt/FensterWohnzimmerL"
    qos: 0
    device_class: battery

  - platform: mqtt
    name: "Wohnzimmerfenster Kontakt R"
    state_topic: 'nodered/alarmkontakte/FensterWohnzimmerR'
    device_class: window

  - platform: mqtt
    name: "Wohnzimmerfenster Kontakt R Batt"
    state_topic: "nodered/batt/FensterWohnzimmerR"
    qos: 0
    device_class: battery
    
  - platform: mqtt
    name: "Wohnzimmertuer Kontakt"
    state_topic: 'nodered/alarmkontakte/Wohnzimmertuer'
    device_class: door

  - platform: mqtt
    name: "Wohnzimmertuer Kontakt Batt"
    state_topic: "nodered/batt/Wohnzimmertuer"
    qos: 0
    device_class: battery
    
sensor:
  - platform: template
    sensors:
      auto_aquarium_start:
        friendly_name: 'Lichter an um '
        value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_rising) - (states("input_number.auto_aquarium_offset_on") | int)  * 60)  | timestamp_custom("%H:%M") }}'
      auto_aquarium_stop:
        friendly_name: 'Lichter aus um '
        value_template: '{{ (as_timestamp("2017-06-09T20:00:00+00:00") + (states("input_number.auto_light_offset_off") | int)  * 60)  | timestamp_custom("%H:%M") }}'


  - platform: min_max
    name: Wohnzimmer Temperatur mid
    entity_ids:
      - sensor.licht_aquarium_bme280_temperatur
      - sensor.wohnzimmer_heizung_sofa_temperature
      - sensor.heizung_wohnzimmer1_temperature

  - platform: mqtt
    name: "Wohnzimmer Temperatur"
    state_topic: aquarium/Sensor/Temperature
    unit_of_measurement: '°C'
    device_class: temperature
    
  - platform: mqtt
    name: "Wohnzimmer Feuchte"
    state_topic: aquarium/Sensor/Humidity
    unit_of_measurement: '%'
    device_class: humidity
    
  - platform: mqtt
    name: "Wohnzimmer Druck"
    state_topic: aquarium/Sensor/Pressure
    device_class: pressure
    unit_of_measurement: "hPa"
    
 
    
media_player:


  - platform: enigma2
    name: VUSolo4K
    port: 81
    host: vusolo4k
 
  - platform: samsungtv_custom
    host: 10.10.0.121
    name: Wohnzimmer-Fernseher
    port: 8002
    mac: B8:BC:5B:26:80:96
    sourcelist: '{"Tuner": "KEY_HDMI1"}'
    applist: "YouTube, Netflix" #(only for QLED and similar)
    protocol: ctl_qled
    
  - platform: onkyo
    host: pioneer-vsx-933-f135fd.steiner.net
    name: Wohnzimmer-Tuner
    sources:
      video1: 'DVD'
      video2: 'SAT'
      video3: 'Game'
      video4: 'BOX'
      network: 'Netzwerk'
      bluetooth: 'Bluetooth'
      usb_usb: 'Usb vorne'
      usb: 'Usb hinten'


    
switch:
  - platform: mqtt
    name: RSH Wohnzimmer
    state_topic: nodered/harmony/rshwohn
    command_topic: nodered/harmony/rshwohn
    qos: 2
    retain: false
    

