
binary_sensor:   
  - platform: mqtt
    name: "Haustuer Kontakt"
    state_topic: 'nodered/alarmkontakte/Haustuer'
    device_class: door

  - platform: mqtt
    name: "Haustuer Kontakt Batt"
    state_topic: "nodered/batt/Haustuer"
    qos: 0
    device_class: battery
 
 
  - platform: mqtt
    name: "Treppenfenster Kontakt"
    state_topic: 'nodered/alarmkontakte/FensterTreppe'
    device_class: window

  - platform: mqtt
    name: "Treppenfenster Kontakt Batt"
    state_topic: "nodered/batt/FensterTreppe"
    qos: 0
    device_class: battery
 
 
  - platform: mqtt
    name: "WC Fenster Kontakt"
    state_topic: 'nodered/alarmkontakte/FensterWc'
    device_class: window

  - platform: mqtt
    name: "WC Fenster Kontakt Batt"
    state_topic: "nodered/batt/FensterWc"
    qos: 0
    device_class: battery





input_number:

  in_temp_flur:
    name: Flurtemperatur
    mode: slider
    min: 18
    max: 24
    step: 0.5